### ISSUE TITLE
Error Messages are Missing in Zod Schema after conversion

### ISSUE THREAD

**Issue by learncourse555** [StefanTerdell/json-schema-to-zod#68] opened 2023-09-12 04:11 UTC
- while converting json schema to zod schema the error messages are missing in it 

### **JSON Schema**
{
  "type": "object",
  "properties": {
    "myString": {
      "type": "string",
      "minLength": 5,
      "errorMessage": {
        "minLength": "Minimum 5 required"
      }
    },
    "myUnion": {
      "type": [
        "number",
        "boolean"
      ]
    }
  },
  "required": [
    "myString",
    "myUnion"
  ],
  "additionalProperties": false,
  "description": "My neat object schema",
  "$schema": "http://json-schema.org/draft-07/schema#"
}

### **ZOD Schema after conversion**
z
  .object({
    myString: z.string().min(5),
    myUnion: z.union([z.number(), z.boolean()]),
  })
  .catchall(z.never())
  .describe("My neat object schema");

**Comment by StefanTerdell** [comment] 2023-11-12 07:35
Duplicate of #50

**Closed by StefanTerdell** 2023-11-12 07:35 UTC
